# Generated by Django 6.0.5 on 2026-06-02 10:42

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='pinned_message',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.CharField(default=api.models.gen_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('type', models.CharField(default='image', max_length=10)),
                ('content', models.TextField()),
                ('viewed_by', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
