# Generated by Django 6.0.5 on 2026-06-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chat_pinned_message_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='pubkey',
            field=models.TextField(blank=True, default=''),
        ),
    ]
