# Generated by Django 6.0.5 on 2026-06-02 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_banneduser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offender_username', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=32)),
                ('term', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True, default='')),
                ('context', models.CharField(default='message', max_length=24)),
                ('chat_id', models.CharField(blank=True, default='', max_length=24)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BannedUser',
        ),
    ]
