# Generated by Django 6.0.5 on 2026-06-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_report_delete_banneduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
